spring.application.name=google-oauth2-sso-restapi


server.port=8080

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

oauth2.authorization-url=/oauth2/authorization/

logging.level.root=INFO
logging.level.com.fragma=DEBUG

# Log file
logging.file.name=logs/oauth-application.log