spring.application.name=google-oauth2-sso-restapi


server.port=8080

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email




spring.security.oauth2.client.registration.cognito.client-id=${AWS_CLIENT_ID}
spring.security.oauth2.client.registration.cognito.client-secret=${AWS_CLIENT_SECRET}
spring.security.oauth2.client.registration.cognito.scope=openid,email,profile
spring.security.oauth2.client.registration.cognito.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.cognito.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.eu-north-1.amazonaws.com/${AWS_USERPOOL_ID}


logging.level.org.springframework=debug